# Generated by Django 5.2 on 2025-04-12 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('tx_hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('credential_hash', models.CharField(max_length=66)),
                ('block_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=100, unique=True)),
                ('public_key', models.TextField()),
                ('encrypted_private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='did', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding_path', models.CharField(max_length=255)),
                ('face_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiableCredential',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('identity', 'Identity Credential'), ('email', 'Email Verification'), ('address', 'Address Verification'), ('employment', 'Employment Verification'), ('education', 'Education Verification'), ('custom', 'Custom Credential')], max_length=20)),
                ('claims', models.JSONField(default=dict)),
                ('signature', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=66, null=True)),
                ('issuance_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('revocation_date', models.DateTimeField(blank=True, null=True)),
                ('issuer_did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_credentials', to='did_app.did')),
                ('subject_did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_credentials', to='did_app.did')),
            ],
        ),
    ]
